bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
'100000': '£100,000',
'200000': '£200,000', 
'300000': '£300,000', 
'400000': '£400,000', 
'500000': '£500,000', 
'600000': '£600,000', 
'700000': '£700,000', 
'800000': '£800,000', 
'900000': '£900,000', 
'1000000': '£1M',
'2000000': '£2M'
}

county_choices = {
'ABD': 'Aberdeenshire, Scotland',
'AGY': 'Anglesey, Wales',
'ANG': 'Angus, Scotland',
'ANT': 'Co. Antrim, Northern Ireland',
'ARL': 'Argyllshire, Scotland',
'ARM': 'Co. Armagh, Northern Ireland',
'AVN': 'Avon, England',
'DC"': 'yrshire, Scotland',
'BAN': 'Banffshire, Scotland',
'BDF': 'Bedfordshire, England',
'BEW': 'Berwickshire, Scotland',
'BKM': 'Buckinghamshire, England',
'BOR': 'Borders, Scotland',
'BRE': 'Breconshire, Wales',
'BRK': 'Berkshire, England',
'BUT': 'Bute, Scotland',
'CAE': 'Caernarvonshire, Wales',
'CAI': 'Caithness, Scotland',
'CAM': 'Cambridgeshire, England',
'CAR': 'Co. Carlow, Ireland',
'CAV': 'Co. Cavan, Ireland',
'CEN': 'Central, Scotland',
'CGN': 'Cardiganshire, Wales',
'CHI': 'Channel Islands (Sometimes just "CI")',
'CHS': 'Cheshire, England',
'CLA': 'Co. Clare, Ireland',
'CLK': 'Clackmannanshire, Scotland',
'CLV': 'Cleveland, England',
'CMA': 'Cumbria, England',
'CMN': 'Carmarthenshire, Wales',
'CON': 'Cornwall, England',
'COR': 'Co. Cork, Ireland',
'CUL': 'Cumberland, England',
'CWD': 'Clwyd, Wales',
'DBY': 'Derbyshire, England',
'DEN': 'Denbighshire, Wales',
'DEV': 'Devon, England',
'DFD': 'Dyfed, Wales',
'DFS': 'Dumfries-shire, Scotland',
'DGY': 'Dumfries and Galloway, Scotland',
'DNB': 'Dunbartonshire, Scotland',
'DON': 'Co. Donegal, Ireland',
'DOR': 'Dorset, England',
'DOW': 'Co. Down, Northern Ireland',
'DUB': 'Co. Dublin, Ireland',
'DUR': 'Co. Durham, England',
'ELN': 'East Lothian, Scotland',
'ERY': 'East Riding of Yorkshire, England',
'ESS': 'Essex, England',
'FIF': 'Fife, Scotland',
'FLN': 'Flintshire, Wales',
'GAL': 'Co. Galway, Ireland',
'GLA': 'Glamorgan, Wales',
'GLS': 'Gloucestershire, England',
'GTM': 'Greater Manchester, England',
'HAM': 'Hampshire, England',
'HRT': 'Hertfordshire, England',
'KEN': 'Kent, England',
'LAN': 'Lancashire, England',
'LND': 'London, England',
'MDX': 'Middlesex, England',
'OXF': 'Oxfordshire, England',
'SRY': 'Surrey, England',
'SSX': 'Sussex, England',
'WAR': 'Warwickshire, England',
'WIL': 'Wiltshire, England',
'WOR': 'Worcestershire, England'
}